"use client";

import { FormEvent } from "react";
import { COPY, DISCOVERIES } from "../game/data";
import type { ChatMessage, Discovery, Lang, NpcDefinition, PanelType } from "../game/types";

type Props = {
  panel: PanelType; npc: NpcDefinition; lang: Lang; chat: ChatMessage[]; question: string; collected: Discovery[]; activeDiscovery?: Discovery;
  summary: string; done: boolean; onClose: () => void; onSpeak: (text: string) => void; onQuestion: (value: string) => void;
  onAsk: (event: FormEvent) => void; onSummary: (value: string) => void; onSubmitDiary: () => void;
};

export default function KnowledgePanels(props: Props) {
  if (!props.panel) return null; const copy = COPY[props.lang]; const found = (id: string) => props.collected.some(item => item.id === id);
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) props.onClose(); }}><section className={`panel ${props.panel}`}><button className="close" onClick={props.onClose}>×</button>
    {props.panel === "npc" && <><div className="npc-head"><div className={`npc-portrait ${props.npc.id}`}><span /></div><div><small>{props.npc.role.toUpperCase()} · NPC</small><h2>{props.npc.name}</h2><p>Warga Trowulan · 1350 M</p></div><button onClick={() => props.chat.at(-1) && props.onSpeak(props.chat.at(-1)!.text)}>◖)))</button></div><div className="chat">{props.chat.map((message, index) => <div key={index} className={message.role}><small>{message.role === "npc" ? props.npc.name.toUpperCase() : "KAMU"}</small><p>{message.text}</p></div>)}</div><div className="suggestions">{[props.lang === "id" ? "Siapa Hayam Wuruk?" : "Who was Hayam Wuruk?", props.lang === "id" ? "Bagaimana tata air kota?" : "How was water managed?", props.lang === "id" ? "Apa makanan sehari-hari?" : "What did people eat?"].map(question => <button key={question} onClick={() => props.onQuestion(question)}>{question}</button>)}</div><form onSubmit={props.onAsk}><input value={props.question} onChange={event => props.onQuestion(event.target.value)} placeholder={copy.ask} /><button>{copy.send} →</button></form></>}
    {props.panel === "fact" && props.activeDiscovery && <><div className="fact-icon">{props.activeDiscovery.icon}</div><p className="eyebrow">{copy.found}</p><h2>{props.activeDiscovery.title}</h2><small>{props.activeDiscovery.year}</small><p className="fact-copy">{props.activeDiscovery.text}</p><div className="fact-progress">{DISCOVERIES.map(discovery => <i key={discovery.id} className={found(discovery.id) ? "on" : ""} />)}</div><button className="primary wide" onClick={props.onClose}>SIMPAN KE DIARY <span>→</span></button></>}
    {props.panel === "diary" && <><div className="diary-title"><p className="eyebrow">CHAPTER 01</p><h2>Time Travel Diary</h2><p>Majapahit · Trowulan · 1350 M</p></div><div className="discovery-list">{DISCOVERIES.map(discovery => <article className={found(discovery.id) ? "found" : ""} key={discovery.id}><b>{discovery.icon}</b><div><small>{found(discovery.id) ? "DITEMUKAN" : "BELUM DITEMUKAN"}</small><strong>{discovery.title}</strong></div><span>{found(discovery.id) ? "✓" : "?"}</span></article>)}</div><label className="summary-label">RANGKUMAN PERJALANAN <span>{props.summary.length}/80 min.</span><textarea value={props.summary} onChange={event => props.onSummary(event.target.value)} placeholder={copy.summary} /></label>{props.done ? <div className="completed">✓ {copy.complete}</div> : <><button className="primary wide" disabled={props.collected.length < 3 || props.summary.trim().length < 80} onClick={props.onSubmitDiary}>{copy.submit} <span>→</span></button>{props.collected.length < 3 && <small className="locked">⌁ {copy.locked}</small>}</>}<details><summary>{copy.sources}</summary><a href="https://whc.unesco.org/en/tentativelists/5466/" target="_blank">UNESCO · Trowulan, Former Capital City of Majapahit</a><a href="https://kebudayaan.kemdikbud.go.id/dpk/sosialisasi-hasil-kajian-zonasi-kcbn-trowulan/" target="_blank">Kemendikbud · Kawasan Cagar Budaya Trowulan</a><a href="https://www.museumnasional.or.id/4388/" target="_blank">Museum Nasional · Celengan Majapahit</a></details></>}
  </section></div>;
}
