"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { CHARACTERS } from "../game/data";
import type { CharacterChoice } from "../game/types";
import CharacterPreview from "./CharacterPreview";
import InfiniteTimeline, { eraAt } from "./InfiniteTimeline";

export default function Launcher({ onLaunch }: { onLaunch: (character: CharacterChoice, avatar: string | null) => void }) {
  const [step, setStep] = useState(0); const [timelineIndex, setTimelineIndex] = useState(1); const [characterIndex, setCharacterIndex] = useState(0); const [avatar, setAvatar] = useState<string | null>(null);
  const character = CHARACTERS[characterIndex]; const selectedEra = useMemo(() => eraAt(timelineIndex), [timelineIndex]);
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file && file.size < 5_000_000) { const reader = new FileReader(); reader.onload = () => setAvatar(String(reader.result)); reader.readAsDataURL(file); } };
  return <div className="launcher"><div className="launch-brand"><span className="brand-mark">OTM</span><span>OUR TIME MACHINE<small>FROM SUPERCONTINENT TO SUPERCONTINENT</small></span></div><div className="stepper"><b className={step >= 0 ? "on" : ""}>01</b><i /><b className={step >= 1 ? "on" : ""}>02</b><i /><b className={step >= 2 ? "on" : ""}>03</b></div>
    {step === 0 && <div className="launch-grid"><section><p className="eyebrow">PILIH TITIK WAKTU</p><h1>Jelajahi<br /><em>jejak bumi.</em></h1><p className="lead">Geser pita waktu tanpa ujung dari satu superbenua ke superbenua berikutnya.</p><div className="timeline"><div className="range-label"><span>LINIMASA SIKLIS BUMI</span><strong>{selectedEra.year}</strong><span>∞ TANPA UJUNG</span></div><InfiniteTimeline index={timelineIndex} onChange={setTimelineIndex} /><div className="era-readout"><small>ZAMAN TERPILIH</small><strong>{selectedEra.label}</strong><span>{selectedEra.detail}</span>{selectedEra.label !== "MAJAPAHIT" && <em>Timeline dapat dijelajahi · gameplay versi ini tetap Majapahit</em>}</div></div></section><div className="earth-wrap"><div className="orbit" /><div className="earth"><i /><i /><i /></div><div className="earth-caption"><small>ZAMAN TERPILIH</small><strong>{selectedEra.year}</strong><span>{selectedEra.label}</span></div></div></div>}
    {step === 1 && <div className="character-step"><section><p className="eyebrow">PILIH KARAKTER PENJELAJAH</p><h1>Siap menembus<br /><em>lorong waktu.</em></h1><div className="character-stage"><button aria-label="Karakter sebelumnya" onClick={() => setCharacterIndex((characterIndex + CHARACTERS.length - 1) % CHARACTERS.length)}>‹</button><CharacterPreview character={character} /><button aria-label="Karakter berikutnya" onClick={() => setCharacterIndex((characterIndex + 1) % CHARACTERS.length)}>›</button></div><div className="character-name"><small>{character.group.toUpperCase()} · MODEL 3D AKTIF</small><strong>{character.name}</strong><span>{characterIndex + 1} / {CHARACTERS.length}</span></div><div className="character-roster">{CHARACTERS.map((item, index) => <button key={item.id} className={index === characterIndex ? "active" : ""} onClick={() => setCharacterIndex(index)} aria-label={`Pilih ${item.name}`}><b>{item.short}</b><small>{item.group}</small></button>)}</div><label className="upload">＋ UNGGAH FOTO PROFIL<input type="file" accept="image/*" onChange={upload} /></label><small>Foto profil bersifat opsional; model pilihan di atas dipakai saat gameplay.</small></section></div>}
    {step === 2 && <div className="destination"><section><p className="eyebrow">KONFIRMASI DESTINASI</p><h1>Kerajaan<br /><em>Majapahit</em></h1><div className="ticket"><div><small>WAKTU</small><strong>1350 M</strong></div><div><small>ERA</small><strong>Nusantara Kuno</strong></div><div><small>WILAYAH</small><strong>Trowulan, Jawa Timur</strong></div><div><small>MISI</small><strong>Stabilkan Retakan Waktu</strong></div></div><div className="safety"><b>✓</b><p><strong>Jendela waktu tidak stabil</strong><span>Temukan 5 benda anomali untuk mengamankan Trowulan</span></p></div></section></div>}
    <footer style={{ position: "fixed" }}><button className="back" disabled={step === 0} onClick={() => setStep(step - 1)}>← KEMBALI</button><p>{step === 0 ? `${selectedEra.label} · ${selectedEra.year}` : step === 1 ? `${character.name} terpilih` : "Misi siap"}</p><button className="primary" onClick={() => step < 2 ? setStep(step + 1) : onLaunch(character, avatar)}>{step < 2 ? "LANJUT" : "READY TO TIME TRAVEL"} <span>→</span></button></footer>
  </div>;
}

